from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field

from schemas.base import EventBase
from schemas.customer_events import (
    CreditLimitUpdated,
    CustomerAssignedToRep,
    CustomerBecameDormant,
    CustomerBecameInactive,
    CustomerChurned,
    CustomerCreated,
    CustomerReactivated,
    CustomerSegmentChanged,
)
from schemas.fraud_events import FraudAlertEvent
from schemas.inventory_events import (
    BackorderFulfilled,
    PurchaseOrderCreated,
    StockoutOccurred,
    StockReceived,
    StockReleased,
    StockReserved,
    SupplierDelay,
)
from schemas.macro_events import AppSessionEvent, MacroStateUpdated, RepVisitCompleted
from schemas.order_events import (
    OrderCancelled,
    OrderConfirmed,
    OrderCreated,
    OrderDelivered,
    OrderLine,
    OrderRejected,
    OrderReturned,
    OrderShipped,
)
from schemas.payment_events import (
    CollectionPromiseMade,
    CollectionScheduled,
    CreditWrittenOff,
    InvoiceCreated,
    PaymentCaptured,
    PaymentFailed,
    PaymentInitiated,
)
from schemas.promotion_events import (
    PromotionActivated,
    PromotionApplied,
    PromotionCreated,
    PromotionExpired,
)

AnyEvent = Annotated[
    Union[
        CustomerCreated,
        CustomerSegmentChanged,
        CustomerReactivated,
        CustomerChurned,
        CustomerBecameInactive,
        CustomerBecameDormant,
        CustomerAssignedToRep,
        CreditLimitUpdated,
        OrderCreated,
        OrderConfirmed,
        OrderShipped,
        OrderDelivered,
        OrderCancelled,
        OrderReturned,
        OrderRejected,
        StockReceived,
        StockReserved,
        StockReleased,
        StockoutOccurred,
        PurchaseOrderCreated,
        SupplierDelay,
        BackorderFulfilled,
        InvoiceCreated,
        PaymentInitiated,
        PaymentCaptured,
        PaymentFailed,
        CollectionScheduled,
        CollectionPromiseMade,
        CreditWrittenOff,
        PromotionCreated,
        PromotionActivated,
        PromotionApplied,
        PromotionExpired,
        FraudAlertEvent,
        MacroStateUpdated,
        RepVisitCompleted,
        AppSessionEvent,
    ],
    Field(discriminator="event_type"),
]

__all__ = [
    "AnyEvent",
    "EventBase",
    "OrderLine",
    "CustomerCreated",
    "CustomerSegmentChanged",
    "CustomerReactivated",
    "CustomerChurned",
    "CustomerBecameInactive",
    "CustomerBecameDormant",
    "CustomerAssignedToRep",
    "CreditLimitUpdated",
    "OrderCreated",
    "OrderConfirmed",
    "OrderShipped",
    "OrderDelivered",
    "OrderCancelled",
    "OrderReturned",
    "OrderRejected",
    "StockReceived",
    "StockReserved",
    "StockReleased",
    "StockoutOccurred",
    "PurchaseOrderCreated",
    "SupplierDelay",
    "BackorderFulfilled",
    "InvoiceCreated",
    "PaymentInitiated",
    "PaymentCaptured",
    "PaymentFailed",
    "CollectionScheduled",
    "CollectionPromiseMade",
    "CreditWrittenOff",
    "PromotionCreated",
    "PromotionActivated",
    "PromotionApplied",
    "PromotionExpired",
    "FraudAlertEvent",
    "MacroStateUpdated",
    "RepVisitCompleted",
    "AppSessionEvent",
]
